export const HTTP_STATUS_CODES: Record<number, string> = {
  100: "Continue",
  101: "Switching Protocols",
  102: "Processing",
  200: "OK",
  201: "Created",
  202: "Accepted",
  204: "No Content",
  206: "Partial Content",
  301: "Moved Permanently",
  302: "Found",
  304: "Not Modified",
  307: "Temporary Redirect",
  308: "Permanent Redirect",
  400: "Bad Request",
  401: "Unauthorized",
  403: "Forbidden",
  404: "Not Found",
  405: "Method Not Allowed",
  408: "Request Timeout",
  409: "Conflict",
  410: "Gone",
  413: "Payload Too Large",
  415: "Unsupported Media Type",
  418: "I'm a teapot",
  422: "Unprocessable Entity",
  429: "Too Many Requests",
  500: "Internal Server Error",
  501: "Not Implemented",
  502: "Bad Gateway",
  503: "Service Unavailable",
  504: "Gateway Timeout",
};

export const MIME_TYPES: Record<string, string> = {
  html: "text/html",
  htm: "text/html",
  css: "text/css",
  js: "application/javascript",
  mjs: "application/javascript",
  json: "application/json",
  xml: "application/xml",
  txt: "text/plain",
  csv: "text/csv",
  pdf: "application/pdf",
  zip: "application/zip",
  gz: "application/gzip",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  svg: "image/svg+xml",
  ico: "image/x-icon",
  mp3: "audio/mpeg",
  mp4: "video/mp4",
  webm: "video/webm",
  woff: "font/woff",
  woff2: "font/woff2",
  ttf: "font/ttf",
  otf: "font/otf",
  wasm: "application/wasm",
  yaml: "application/yaml",
  yml: "application/yaml",
  md: "text/markdown",
  ts: "text/typescript",
  tsx: "text/typescript",
};

export const GITIGNORE_TEMPLATES: Record<string, string> = {
  node: "node_modules/\n.env\n.env.*\ndist/\nbuild/\n*.log\n.DS_Store\ncoverage/\n",
  python: "__pycache__/\n*.py[cod]\n.venv/\nvenv/\n.env\n*.egg-info/\n.pytest_cache/\n",
  java: "target/\n*.class\n*.jar\n.idea/\n*.iml\n",
  go: "bin/\n*.exe\n*.test\nvendor/\n",
  rust: "target/\nCargo.lock\n",
  dotnet: "bin/\nobj/\n*.user\n*.suo\n.vs/\n",
  react: "node_modules/\nbuild/\ndist/\n.env\n.env.local\n",
  vue: "node_modules/\ndist/\n.env\n*.local\n",
  docker: ".env\n*.log\ndata/\n",
};

export const DOCKERIGNORE_TEMPLATES: Record<string, string> = {
  node: "node_modules\nnpm-debug.log\n.git\n.env\n*.md\ncoverage\n",
  python: "__pycache__\n*.pyc\n.venv\nvenv\n.git\n.env\n*.md\n",
  general: ".git\n.gitignore\n*.md\n.env\n.env.*\nDockerfile*\ndocker-compose*\n",
};

export const REGEX_PATTERNS: { id: string; pattern: string; flags: string }[] = [
  { id: "email", pattern: "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$", flags: "" },
  { id: "url", pattern: "^https?:\\/\\/[\\w.-]+(?:\\.[\\w.-]+)+[\\w\\-._~:/?#[\\]@!$&'()*+,;=.]*$", flags: "" },
  { id: "ipv4", pattern: "^(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)$", flags: "" },
  { id: "phone", pattern: "^\\+?[1-9]\\d{6,14}$", flags: "" },
  { id: "hexColor", pattern: "^#(?:[0-9a-fA-F]{3}){1,2}$", flags: "" },
  { id: "uuid", pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$", flags: "i" },
  { id: "dateIso", pattern: "^\\d{4}-\\d{2}-\\d{2}$", flags: "" },
  { id: "slug", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$", flags: "" },
];

export const LOREM_WORDS =
  "lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum".split(
    " ",
  );
